platform :ios, '8.0'
target "ShowNews" do
pod 'RESideMenu', '~> 4.0.7'
pod 'MJRefresh', '~> 3.1.7'
pod 'BaiduMapKit', '~> 3.0.0'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'AFNetworking', '~> 3.1.0'
pod 'Masonry', '~> 1.0.1'
pod 'SMPageControl', '~> 1.2'
pod 'UMengSocialCOM', '~> 5.2.1'
end
